// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ProjectSubmission.Models;
using System;

namespace ProjectSubmission.Migrations
{
    [DbContext(typeof(ProjectSubmissionContext))]
    partial class ProjectSubmissionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectSubmission.Models.Submissions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("refTicket");

                    b.Property<string>("submission");

                    b.Property<string>("submitter");

                    b.Property<int>("votes");

                    b.HasKey("ID");

                    b.ToTable("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
